/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package saberfight;

/**
 *
 * @author sasukeuni
 */
public class Panel extends javax.swing.JPanel {

    /**
     * Creates new form panel
     */
    public Panel() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jSplitPane3 = new javax.swing.JSplitPane();
        Left = new javax.swing.JLabel();
        Right = new javax.swing.JLabel();
        Bottom = new javax.swing.JLabel();

        jSplitPane1.setDividerLocation(500);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jSplitPane3.setDividerLocation(400);

        Left.setFont(new java.awt.Font("Tahoma", 0, 100)); // NOI18N
        Left.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Left.setText("0");
        jSplitPane3.setLeftComponent(Left);

        Right.setFont(new java.awt.Font("Tahoma", 0, 100)); // NOI18N
        Right.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Right.setText("0");
        jSplitPane3.setRightComponent(Right);

        jSplitPane1.setTopComponent(jSplitPane3);

        Bottom.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        Bottom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bottom.setText("Bottom (Texto de las condiciones)");
        jSplitPane1.setRightComponent(Bottom);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel Bottom;
    public static javax.swing.JLabel Left;
    public static javax.swing.JLabel Right;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane3;
    // End of variables declaration//GEN-END:variables

    private static String SLeft;
    private static String SRight;
    private static String SBottom;

    public static void setLeft() {

//        SLeft=Left.getText();
        if (SaberFight.isAPressed()) {
            Left.setText(Left.getText()+1);
            try {
                Thread.sleep(10000);                 //1000 milliseconds is one second.
            } catch (InterruptedException ex) {
                Thread.currentThread().interrupt();
            }

        }

    }

    public static void setRight() {
//        SRight=Right.getText();

        if (SaberFight.isDPressed()) {
            Right.setText(String.valueOf(Right.getText()+1));
            try {
                Thread.sleep(10000);                 //1000 milliseconds is one second.
            } catch (InterruptedException ex) {
                Thread.currentThread().interrupt();
            }

        }

    }

    public void setBottom() {

    }

}
